- hosts: mysql
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    andrew
  roles:
    - geerlingguy.mysql


  environment:
     http_proxy: http://zenov.website:8118
     https_proxy: http://zenov.website:8118