# https://www.dmosk.ru/miniinstruktions.php?mini=ansible-roles-example#grafana
---
- name: Security Settings And Install Grafana
  block:
    - name: Allow TCP Ports
      iptables:
        chain: INPUT
        rule_num: '1'
        action: insert
        protocol: tcp
        jump: ACCEPT
        destination_port: '3000'

    - name: Import Grafana Apt Key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add APT Repository
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present

    - name: Install Grafana on Debian Family
      apt:
        name: grafana
        state: present
      notify:
        - grafana systemd

- name: Create Directories For Grafana
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop:
    - '/etc/grafana/provisioning/'
    - '/etc/grafana/provisioning/datasources'

- name: Configuring Grafana (dashboard)
  copy:
    src: templates/dashboard.yml
    dest: /etc/grafana/provisioning/dashboards
    owner: root
    group: root
    mode: '0644'
- name: Configuring Grafana (datasource)
  copy:
    src: templates/datasource.yml
    dest: /etc/grafana/provisioning/datasources
    owner: root
    group: root
    mode: '0644'
- name: Configuring Grafana (dashboard node_exporter)
  copy:
    src: templates/node-exporter-full_rev27.json
    dest: /etc/grafana/provisioning/dashboards
    owner: root
    group: root
    mode: '0644'



