---

# Set this to the user ansible is logging in as - should have root
# or sudo access
mysql_user_home: /home/andrew
mysql_user_name: andrew
mysql_user_password: andrew

# Set this to `true` to forcibly update the root password.
mysql_root_password_update: false
mysql_user_password_update: false

mysql_databases:
   - name: wordpress
     collation: utf8_general_ci
     encoding: utf8
     replicate: 1

# Users.
mysql_users:
   - name: wordpress
     host: '%'
     password: wordpress
     priv: '*.*:ALL PRIVILEGES'

   - name: wordpress_res
     password: wordpress
     priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'

mysql_replication_master: 'db01.zenov.website'

mysql_replication_user:
   name: wordpress_res
   password: wordpress
