---
- name: firewalld systemd restart
  command: firewall-cmd --reload

- name: systemd reload
  systemd:
    daemon_reload: yes

- name: grafana systemd
  systemd:
    name: grafana-server
    enabled: yes
    state: started
